server:
  port: 9000

spring:
  application:
    name: cards-service
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3308/cards-db
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: '*'